[
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-14T21:24:26|,
    "ALERT_TRANSACTION_ID": 170,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 3
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-14T21:24:26|,
    "ALERT_TRANSACTION_ID": 171,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 7
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-14T22:54:05|,
    "ALERT_TRANSACTION_ID": 188,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 3
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-14T22:54:04|,
    "ALERT_TRANSACTION_ID": 189,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 8
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-14T22:54:03|,
    "ALERT_TRANSACTION_ID": 190,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 16
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-15T20:10:26|,
    "ALERT_TRANSACTION_ID": 199,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 2
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-15T21:19:53|,
    "ALERT_TRANSACTION_ID": 205,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 2
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-15T21:29:42|,
    "ALERT_TRANSACTION_ID": 216,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 2
  },
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-15T21:29:42|,
    "ALERT_TRANSACTION_ID": 217,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 3
  }
]