[
  {
    "SUBSCRIPTION_ID": 5024,
    "DELAY_TYPE_FLAG": "1",
    "NOTIFICATION_FAILURE_DETAIL": "NA",
    "CREATION_TIMESTAMP": |2022-04-15T20:10:26|,
    "ALERT_TRANSACTION_ID": 199,
    "NOTIFICATION_STATUS": "Sent",
    "DELAY_TIME": 2
  }
]